name: VisualPing
version: '${version}'
main: com.bzvzn.visualping.VisualPing
api-version: '26.1.2'
description: A visual ping system for players to highlight locations.
author: Bzvzn
commands:
  pingcolor:
    description: Change the color of your visual ping!
    usage: /pingcolor <#HEXCODE>
  pingreload:
    description: Reload the VisualPing configuration.
    usage: /pingreload
    permission: visualping.reload
    permission-message: §cYou do not have permission to execute this command.